### ISSUE TITLE
Encountered an error while attempting to download the dataset.

### ISSUE THREAD

**Issue by Lizhe1228** [xinyiyu/Nudiff#1]
我对你们的工作很感兴趣，想尝试复现一下实验，当我请求下载数据集时，提示我需要申请权限，现我已申请权限，希望能得到通过谢谢，我的账号是lizhe2339@gmail.com
I'm very interested in your work and have been trying to replicate the experiment. When I attempted to download the dataset, I received a message stating that I need to request permission. I have now applied for access, and I hope it can be approved. Thank you. My account is [lizhe2339@gmail.com](mailto:lizhe2339@gmail.com)
![image](https://github.com/xinyiyu/Nudiff/assets/58848764/d8808de3-4e30-491f-851d-f7a2fb280674)

**Comment by xinyiyu** [comment]
Hello! I have approved your access request and have updated the data link's access permissions. Please check if you are now able to download the data.
