### ISSUE TITLE
inputs of distance transform 

### ISSUE THREAD

**Issue by Kedaya66** [xinyiyu/Nudiff#4]
Dear author：
I am writing to ask what are the inputs for distance transform. Thanks！

**Comment by Kedaya66** [comment]
And it seems i could't find the function "get_hv" (vertical and horizantal distance) is used in the jupyternotebook or other places.

**Comment by xinyiyu** [comment]
In the first cell of the notebook, there is one sentence "from nudiff.image_syn.utils.datasets import get_hv". I have checked that the function "get_hv" is in the file "nudiff/image_syn/utils/datasets.py". The input of "get_hv" (to compute distance transform) is the instance map.

You can try to import the function again or directly copy the function to wherever you need to use it.
